"""add profile settings

Revision ID: 6dffe160999c
Revises: f1346073ac16
Create Date: 2026-09-21 01:15:29.926491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dffe160999c'
down_revision: Union[str, Sequence[str], None] = 'f1346073ac16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_settings_id'), 'reminder_settings', ['id'], unique=False)
    op.create_index(op.f('ix_reminder_settings_user_id'), 'reminder_settings', ['user_id'], unique=True)
    op.create_table('training_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_goals_id'), 'training_goals', ['id'], unique=False)
    op.create_index(op.f('ix_training_goals_user_id'), 'training_goals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_goals_user_id'), table_name='training_goals')
    op.drop_index(op.f('ix_training_goals_id'), table_name='training_goals')
    op.drop_table('training_goals')
    op.drop_index(op.f('ix_reminder_settings_user_id'), table_name='reminder_settings')
    op.drop_index(op.f('ix_reminder_settings_id'), table_name='reminder_settings')
    op.drop_table('reminder_settings')
    # ### end Alembic commands ###
