"""make phone age gender required

Revision ID: f1346073ac16
Revises: 0408806d7ad3
Create Date: 2026-09-19 04:53:36.486847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1346073ac16'
down_revision: Union[str, Sequence[str], None] = '0408806d7ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
